HW14
dmitryt/otus-golang-hw pull request #13
Opened 2020-08-29 13:24 UTC by dmitryt

## Домашнее задание №14 «Кроликизация Календаря»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Работа с RMQ выделена в отдельный пакет, код не дублируется - 1 балл
- [ ] Реализован Рассыльщик - 2 балла
- [ ] Можно собрать сервисы одной командой (`make build`) - 1 балл 
- [ ] Понятность и чистота кода - до 2 баллов

Реализован Планировщик:
- [ ] отсылает уведомления о выбранных событиях - 2 балла
- [ ] удаляет старые события - 1 балл
    
#### Зачёт от 7 баллов

2020-09-07 18:05 UTC, kulti requested changes
Код понятно разбит по пакетам. Довольно легко и удобно находить нужный кусок. Работа с очередью хорошо отделена от приложения, хоть и не совсем четко.

Есть одна серьезная проблема (пометил ее восклицательными знаками) — поэтому Request changes. Остальные замечания скорее для будущих проектов.

Когда поправите проблему бесконечным запуском горутин, то приму ДЗ с 9/10.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +		// TODO: Implement reconnecting
Идеи для реконнекта к рэббиту можно посмотреть в этой статье - https://medium.com/@dhanushgopinath/automatically-recovering-rabbitmq-connections-in-go-applications-7795a605ca59.

Достаточно толково все расписано. Я опирался на нее, когда реализовывал реконнект в своем приложении. Единственное, что мне не понравилось — канал `c.err`. По сути, он в примере никак не используется и выглядит лишним, т.к. уже есть канал из `<-c.conn.NotifyClose()`. Возможно, в их большом приложении дополнительный канал имеет смысл.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/queue/queue.go
> +	return fmt.Sprintf("amqp://%s:%s@%s:%s/", args...)
Очень "грязная" функция. Формат завязан на конкретное число аргументов, а передается variadic.

Есть ли вообще смысл разбивать конфигурацию соединения к очереди на части в конфиге, чтобы потом здесь собирать ampq-URL? Мне, обычно, проще и удобнее было задавать в конфиге только целый ampq-URL.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/migrations/20200816153151_init.sql
> + notified_for INT NOT NULL default 1,
На всякий случай напишу, что файлы миграции нельзя править (только, если в них не было ошибки). Для удаления колонки и добавления новой нужно писать отдельную миграцию.

В учебном или еще не готовом проекте такое изменение не страшно.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/service/schema/calendar.proto
> + int64 NotifiedFor = 7;
Опять же, пишу на всякий случай, что это обратно несовместимые изменения. Новое поле NotifiedFor должно быть с номером 8.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/sender/app.go
> +		log.Error().Msgf("%s: %s", ErrDecodeIncomingMessage, err)
Очень странная конструкция. `ErrDecodeIncomingMessage` - это error, и `err` тоже error. Какой смысл в `ErrDecodeIncomingMessage` совсем не понимаю. Можно сделать просто `log.Error().Msgf("cannot decode incoming message: %s", ErrDecodeIncomingMessage, err)`

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +		go fn(msgs)
❗❗❗
Здесь в цикле будут постоянно запускаться горутины. Этот код просто не будет работать, как ожидалось.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +func (c *Consumer) Handle(fn func(<-chan amqp.Delivery)) error {
Какая-то сильно перекрученная логика получилась.

Метод называется Handle — неочевидно, что внутри обработка будет в горутине. В местах, где вызывается Handle, передается какой-то метод. Если не посмотреть внутрь Handle, то совершенно непонятно, что происходит и как работает.

В одном из дискашенов скинул статью про реконнект. Можно посмотреть, как там сделано.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/cmd/calendar_sender/main.go
> +		qCfg.QueueName,
Очень странно видеть QueueName для четырех параметров. Думаю, стоит получше разобраться, как работать с очередью (у rabbitmq отличные туториалы — https://www.rabbitmq.com/tutorials/tutorial-one-go.html).

Для этой задачи можно обойтись дефолтным топиком. Т.е. никакие дополнительные эксченжи, топики и биндинги можно не делать.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +		nil,
А amqp ужасное API. Рекомендую придерживаться стиля, который у них в туториалах и рядом с флагами писать комментарий, что это за флаг:
```
queue, err := ch.QueueDeclare(
  c.queueName,
  true,    // durable
  false,   // delete when unused
  false,   // exclusive
  false,   // no-wait
  nil,     // arguments
)
```

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/scheduler/app.go
> +	scanTimeout int
По названию непонятно, в чем измеряется scanTimeout. Лучше дописывать в название Sec,Ms etc или использовать тип time.Duration.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/scheduler/app.go
> +			go func() {
Не нужно запускать отдельные горутины просто так. Это ничего не даст и может наоборот ухудшить производительность, т.к. они начнут бороться за один ресурс — БД.

Если processEvents и/или DeleteObsoleteEvents будут работать дольше, чем сработает тикер, то количество горутин будет постоянно расти.

2020-09-07 18:05 UTC, kulti commented on hw12_13_14_15_calendar/internal/scheduler/app.go
> +					errCh <- err
Не уверен, что это хороший паттерн. В чем смысл? Если "улучшить производительность", то сомневаюсь, что это поможет и имеет хоть какой-то смысл, т.к. ошибки — это редкий случай. Возможно, если сделать канал errCh буферизованным, то будут амортизироваться всплески и здесь можно будет дропать ошибки, если не получается записать в канал:
```
select {
  case errCh <- err:
  default:
}
```

2020-09-07 18:37 UTC, dmitryt commented on hw12_13_14_15_calendar/migrations/20200816153151_init.sql
> + notified_for INT NOT NULL default 1,
Можно сказать, что это еще не готовый проект :) Поэтому не хотел заморачиваться с отдельными миграциями

2020-09-07 18:39 UTC, dmitryt commented on hw12_13_14_15_calendar/internal/sender/app.go
> +		log.Error().Msgf("%s: %s", ErrDecodeIncomingMessage, err)
Просто вынес ошибку наверх, но наверное действительно проще описание ошибки внутрь положить

2020-09-07 18:42 UTC, dmitryt commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +		nil,
это конечно лучше, но не убережет от будущих проблем - скажем, когда/если API изменится, то некоторые комментарии будут отвечать за неправильные ключи

2020-09-08 08:05 UTC, kulti commented on hw12_13_14_15_calendar/migrations/20200816153151_init.sql
> + notified_for INT NOT NULL default 1,
Ну, да. Я так и подумал :) Но предпочитаю не предполагать и на всякий случай все проговорить. Телепатия - путь к недопониманию :)

2020-09-08 08:08 UTC, kulti commented on hw12_13_14_15_calendar/internal/queue/consumer.go
> +		nil,
Breaking changes маловероятны для подобного публичного API маловероятно.

А если все такие изменится, то в этом месте тоже будут правки. Соответственно и комменты будут актуальными. Если API изменится так, что один флаг просто заменят на другой, то за такие изменения никто спасибо не скажет и проблемы будут куда серьезнее и уж точно не из-за неверных комментариев :)

2020-09-09 16:44 UTC, kulti approved these changes
Самая серьезная проблема пофикшена. ДЗ принято - 9/10.

2020-09-09 16:47 UTC, merged