init
dmitryt/otus-golang-hw pull request #9
Opened 2020-08-09 22:01 UTC by dmitryt

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-08-14 18:32 UTC, kulti requested changes
Добрый день.

Начал делать ревью и понял, что задание неправильно понято. Попробую объяснить, чем отличается пайплайн обработка от текущего решения.

В этом коде выбирается значение из канала и прогоняется по всем стейджам.

В пайплайн подходе нужно собрать цепочку из стейджей и входного и выходного каналов, чтобы значение бралось первый стейджом из входного канала, результат передавался в следующий стейдж и т.д., пока не попадет в выходной канал.

Если не получается понять, то приходите в личку в слаке, задавайте вопросы - постараюсь объяснить по другому.

2020-08-14 18:32 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	return fillResult(d.values, i)
Метод `ExecutePipeline` возвращает канал. Такая сигнатура говорит, что результаты должны отправляться по мере готовности, а не все сразу. Иначе в канале нет смысла - можно просто вернуть слайс с результатами.

2020-08-14 18:32 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +func checkDone(done In) Bi {
Этот метод лишний.

Если в метод передают канал или контекс для предварительного завершения, то он уже реализует семантику броадкаста. Т.е. канал done закроют, а не будут писать в него одно значение.

2020-08-15 11:40 UTC, dmitryt commented on hw06_pipeline_execution/pipeline.go
> +func checkDone(done In) Bi {
согласен, просто не подтянул последние результаты с мастера

2020-08-16 13:03 UTC, kulti approved these changes
Теперь по коду все отлично. ДЗ принято - 8/10.

Если хотите 10 баллов, то нужно добавить юнит-тесты.

2020-08-16 16:13 UTC, merged